services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/etc/nginx/logs
      - ./www:/etc/nginx/html
#      - ./cache:/var/cache/nginx
    ports:
      - '8080:8080'
# /etc/nginx/html/index.html
