services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/var/log/nginx
      - ./assets:/var/www/html
    ports:
      - '8080:8080'
